'use strict';

const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {after,before,test}=require('node:test');
const {DatabaseSync}=require('node:sqlite');
const {readBaseline,readOverlay,runImport}=require('../src/data/importer');
const {EXPECTED_SERIES,validateDatabase}=require('../src/data/validator');
const queries=require('../src/data/queries');

const root=fs.mkdtempSync(path.join(os.tmpdir(),'zhsh-full-static-'));
const databasePath=path.join(root,'content.sqlite');
const baselinePath=path.resolve('docs/reconstruction-baseline/multisource-baseline.json');
const overlayPath=path.resolve('docs/reconstruction-baseline/restoration-resolution-overlay.json');
const repositoryBytes=(file)=>Buffer.from(fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n'));
const baselineHashBefore=crypto.createHash('sha256').update(repositoryBytes(baselinePath)).digest('hex');
let firstReport;let db;

before(()=>{firstReport=runImport({databasePath});db=new DatabaseSync(databasePath);db.exec('PRAGMA foreign_keys=ON');});
after(()=>{db?.close();fs.rmSync(root,{recursive:true,force:true});});

test('baseline and overlay schemas validate before import',()=>{assert.equal(readBaseline(baselinePath).baseline.meta.schema_version,'2.0.0');assert.equal(readOverlay(overlayPath).overlay.schema_version,'1.0.0');});
test('baseline file remains repository-byte unchanged across platform line endings',()=>{assert.equal(crypto.createHash('sha256').update(repositoryBytes(baselinePath)).digest('hex'),baselineHashBefore);assert.equal(baselineHashBefore,'1f8d033e60895bccfd2a992cc34d1b6f51e191746fa4e02ec92b04579b4efbe5');});
test('overlay references exactly the three approved evidence records',()=>{const r=readOverlay(overlayPath).overlay.resolutions[0];assert.deepEqual(r.evidence_canonical_ids,['entity.location_connection.bcedd08f9944c48b','entity.npc_placement.8b4f15b70705a612','entity.trial.2a7f00d4dd269f27']);assert.equal(Number(db.prepare('SELECT COUNT(*) count FROM resolution_evidence').get().count),3);});
test('baseline, derived and formal locations count 641, 1 and 642',()=>{assert.equal(Number(db.prepare('SELECT COUNT(*) count FROM locations WHERE is_derived=0').get().count),641);assert.equal(Number(db.prepare('SELECT COUNT(*) count FROM locations WHERE is_derived=1').get().count),1);assert.equal(firstReport.entity_counts.locations,642);});
test('Niutoushan entrance connection and guard placement are queryable',()=>{assert.equal(db.prepare("SELECT runtime_capability FROM location_connections WHERE canonical_id='entity.location_connection.bcedd08f9944c48b'").get().runtime_capability,'queryable');const p=db.prepare("SELECT runtime_capability,location_id FROM npc_placements WHERE canonical_id='entity.npc_placement.8b4f15b70705a612'").get();assert.equal(p.runtime_capability,'queryable');assert.notEqual(p.location_id,null);});
test('no unresolved map node remains',()=>{assert.equal(Number(db.prepare("SELECT COUNT(*) count FROM map_nodes WHERE node_kind NOT IN ('city','location')").get().count),0);});
test('trial internal floor labels are not ordinary world locations',()=>{assert.equal(Number(db.prepare("SELECT COUNT(*) count FROM locations WHERE display_name GLOB '牛头山第*层'").get().count),0);assert.ok(queries.trialDetails(db,'牛头山').stage_labels.some(x=>x.raw_label==='牛头山第一层'&&x.resolution_status==='source_label_only'));});
test('all baseline static entities are imported at exact counts',()=>{assert.deepEqual(firstReport.baseline_entity_counts,{world_regions:6,cities:40,locations:641,location_connections:627,npc_placements:636,items:153,equipment:423,monsters:278,drops:2732,shops:63,city_price_ranges:54,ships:14,fish:21,pets:8,trials:12});assert.equal(firstReport.entity_counts.story_nodes,20);assert.equal(firstReport.entity_counts.system_rules,26);});
test('all 651 tasks and all 15 series are imported',()=>{assert.equal(firstReport.entity_counts.task_definitions,651);const counts=Object.fromEntries(db.prepare('SELECT s.source_series,COUNT(t.id) count FROM task_series s JOIN task_definitions t ON t.task_series_id=s.id GROUP BY s.id').all().map(r=>[Number(r.source_series),Number(r.count)]));assert.deepEqual(counts,EXPECTED_SERIES);});
test('explicit prerequisites are acyclic',()=>{const edges=db.prepare('SELECT task_id,prerequisite_task_id FROM task_prerequisites').all();const pred=new Map(edges.map(e=>[Number(e.task_id),Number(e.prerequisite_task_id)]));for(const start of pred.keys()){const seen=new Set();let cur=start;while(pred.has(cur)){assert.equal(seen.has(cur),false,`cycle at ${start}`);seen.add(cur);cur=pred.get(cur);}}});
test('no cross-series prerequisite is invented',()=>{assert.equal(Number(db.prepare('SELECT COUNT(*) count FROM task_prerequisites p JOIN task_definitions a ON a.id=p.task_id JOIN task_definitions b ON b.id=p.prerequisite_task_id WHERE a.task_series_id<>b.task_series_id').get().count),0);});
test('unresolved and cross-type labels are preserved without fabricated entities',()=>{assert.equal(Number(db.prepare("SELECT COUNT(*) count FROM content_entities WHERE display_name='声望'").get().count),0);assert.equal(Number(db.prepare("SELECT COUNT(*) count FROM monster_definitions WHERE display_name IN ('白云果','破碎的破界符')").get().count),0);for(const status of ['resolved','ambiguous','source_label_only','cross_type_suspected','blocked_missing_definition'])assert.ok(firstReport.dependency_resolution_counts[status]>0,status);});
test('same-name items remain separate and resolution records every candidate',()=>{const count=Number(db.prepare("SELECT COUNT(*) count FROM content_entities WHERE entity_category='item' AND display_name='潜水镜'").get().count);assert.equal(count,2);const ref=db.prepare("SELECT resolution_status,candidate_canonical_ids_json FROM dependency_references WHERE source_canonical_id='task.series.01.007' AND reference_context='task_target'").get();assert.equal(ref.resolution_status,'resolved');assert.equal(JSON.parse(ref.candidate_canonical_ids_json).length,2);});
test('all 32 conflicts remain unresolved',()=>{assert.equal(Number(db.prepare('SELECT COUNT(*) count FROM restoration_conflicts').get().count),32);assert.equal(Number(db.prepare("SELECT COUNT(*) count FROM restoration_conflicts WHERE runtime_policy='unresolved' AND selected_candidate_json IS NULL").get().count),32);});
test('first import has no foreign-key violations and every formal entity is traceable',()=>{assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);assert.equal(queries.provenance(db,'derived.location.7a7f7b6127a89313').resolution.evidence_canonical_ids.length,3);assert.equal(queries.provenance(db,'task.series.15.560').record_origin,'baseline');});
test('second full import inserts and updates zero rows',()=>{const report=runImport({databasePath});assert.equal(report.operations.inserted,0);assert.equal(report.operations.updated,0);assert.deepEqual(report.entity_counts,firstReport.entity_counts);});
test('dry-run writes no database file',()=>{const p=path.join(root,'dry.sqlite');const report=runImport({databasePath:p,dryRun:true});assert.equal(report.dry_run,true);assert.equal(report.entity_counts.task_definitions,651);assert.equal(fs.existsSync(p),false);});
test('static scope imports complete non-task content and no task definitions',()=>{const report=runImport({databasePath:path.join(root,'static.sqlite'),dryRun:true,scope:'static'});assert.equal(report.entity_counts.locations,642);assert.equal(report.entity_counts.drop_relations,2732);assert.equal(report.entity_counts.task_definitions,0);});
test('task-series selection imports the exact selected series',()=>{const report=runImport({databasePath:path.join(root,'series15.sqlite'),dryRun:true,taskSeries:'15'});assert.equal(report.entity_counts.task_series,1);assert.equal(report.entity_counts.task_definitions,470);});
test('missing overlay evidence rolls back the entire content transaction',()=>{const badPath=path.join(root,'bad-overlay.json');const overlay=readOverlay(overlayPath).overlay;overlay.resolutions[0].evidence_canonical_ids[0]='entity.missing.evidence';fs.writeFileSync(badPath,`${JSON.stringify(overlay,null,2)}\n`,'utf8');const rollback=path.join(root,'rollback.sqlite');assert.throws(()=>runImport({databasePath:rollback,overlayPath:badPath}),/Missing overlay evidence/);const checkDb=new DatabaseSync(rollback);try{assert.equal(Number(checkDb.prepare('SELECT COUNT(*) count FROM restoration_records').get().count),0);assert.equal(Number(checkDb.prepare('SELECT COUNT(*) count FROM locations').get().count),0);}finally{checkDb.close();}});
test('automated validator passes every full-import check',()=>{const result=validateDatabase(db,{baselinePath,overlayPath});assert.equal(result.passed,true,result.checks.filter(x=>!x.passed).map(x=>x.name).join(','));assert.ok(result.checks.length>=18);});
test('tested runtime provides built-in node:sqlite',()=>{const [major,minor]=process.versions.node.split('.').map(Number);assert.ok(major>22||(major===22&&minor>=5));assert.equal(typeof DatabaseSync,'function');});
test('development query surface covers derived provenance and all task series',()=>{assert.ok(queries.cityLocations(db,'荷姆兹').some(x=>x.canonical_id==='derived.location.7a7f7b6127a89313'));assert.ok(queries.adjacentLocations(db,'荷姆兹-牛头山入口').length>0);assert.ok(queries.locationNpcs(db,'荷姆兹-牛头山入口').some(x=>x.display_name==='牛头山守卫'));assert.equal(queries.taskSeries(db,'task.series.15').length,470);assert.equal(queries.taskDetails(db,'task.series.01.007').targets[0].raw_name,'潜水镜');});
